// apps/web/src/app/[locale]/dashboard/invoices/page.tsx
'use client';

import { useTranslations } from 'next-intl';
import { useState, useEffect } from 'react';

interface Invoice {
  id: string;
  amount: number;
  status: string;
  dueDate: string;
  createdAt: string;
  student?: { name: string };
  client?: { name: string };
  _count?: { events: number; lessons: number };
}

interface Client {
  id: string;
  name: string;
}

const STATUS_CLASS: Record<string, string> = {
  PENDING: 'bg-amber-100 text-amber-700',
  PAID: 'bg-green-100 text-green-700',
  OVERDUE: 'bg-red-100 text-red-700',
  REFUNDED: 'bg-gray-100 text-gray-600',
};

export default function InvoicesPage() {
  const t = useTranslations();
  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [clients, setClients] = useState<Client[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ clientId: '', amount: '', dueDate: '' });

  const loadData = () => {
    setLoading(true);
    setError(null);
    Promise.all([
      fetch('/api/invoices').then((r) => r.json()),
      fetch('/api/clients').then((r) => r.json()),
    ])
      .then(([invoicesData, clientsData]) => {
        if (invoicesData.error) throw new Error(invoicesData.error);
        if (clientsData.error) throw new Error(clientsData.error);
        setInvoices(invoicesData);
        setClients(clientsData);
      })
      .catch((e) => {
        // If one API failed, try to salvage partial results
        setError(e.message || String(e));
      })
      .finally(() => setLoading(false));
  };

  useEffect(loadData, []);

  const totalRevenue = invoices
    .filter((i) => i.status === 'PAID')
    .reduce((s, i) => s + i.amount, 0);
  const pendingCount = invoices.filter((i) => i.status === 'PENDING').length;
  const overdueCount = invoices.filter((i) => i.status === 'OVERDUE').length;

  const statusLabel = (status: string): string => {
    const key = `invoices.status.${status}`;
    const label = t(key);
    // fallback: if the key wasn't translated (returned raw key), show status directly
    return label === key ? status : label;
  };

  const clientName = (inv: Invoice): string => {
    return inv.client?.name || inv.student?.name || t('invoices.noClient') || 'Unknown';
  };

  const handleAdd = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!form.clientId || !form.amount) return;
    try {
      const res = await fetch('/api/invoices', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          clientId: form.clientId,
          amount: parseFloat(form.amount),
          dueDate:
            form.dueDate ||
            new Date(Date.now() + 7 * 86400000).toISOString().split('T')[0],
        }),
      });
      if (res.ok) {
        setShowForm(false);
        setForm({ clientId: '', amount: '', dueDate: '' });
        loadData();
      }
    } catch {
      /* swallow */
    }
  };

  if (loading) {
    return (
      <div className="animate-pulse space-y-4">
        <div className="h-8 w-48 bg-gray-200 rounded" />
        <div className="grid grid-cols-3 gap-4">
          {[...Array(3)].map((_, i) => (
            <div key={i} className="h-24 bg-gray-100 rounded-xl" />
          ))}
        </div>
        {[...Array(3)].map((_, i) => (
          <div key={i} className="h-20 bg-gray-100 rounded-xl" />
        ))}
      </div>
    );
  }

  if (error) {
    return (
      <div className="bg-red-50 border border-red-200 rounded-xl p-4 text-red-700 text-sm">
        {t('error.desc')}: {error}
        <button
          onClick={loadData}
          className="ml-2 underline font-medium hover:text-red-900"
        >
          {t('error.retry')}
        </button>
      </div>
    );
  }

  return (
    <div>
      {/* Header */}
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-2xl font-bold">{t('dashboard.invoices')}</h1>
        <button
          onClick={() => setShowForm(true)}
          className="bg-indigo-600 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-indigo-700 transition-colors"
        >
          + {t('invoices.addNew') || 'New Invoice'}
        </button>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-3 gap-4 mb-6">
        <div className="bg-white rounded-xl border p-4 text-center">
          <div className="text-2xl font-bold text-green-600">
            ${totalRevenue.toFixed(0)}
          </div>
          <div className="text-xs text-gray-500 mt-1">
            {t('invoices.totalRevenue') || 'Total Revenue'}
          </div>
        </div>
        <div className="bg-white rounded-xl border p-4 text-center">
          <div className="text-2xl font-bold text-amber-600">
            {pendingCount}
          </div>
          <div className="text-xs text-gray-500 mt-1">
            {t('invoices.pending') || 'Pending'}
          </div>
        </div>
        <div className="bg-white rounded-xl border p-4 text-center">
          <div className="text-2xl font-bold text-red-600">
            {overdueCount}
          </div>
          <div className="text-xs text-gray-500 mt-1">
            {t('invoices.overdue') || 'Overdue'}
          </div>
        </div>
      </div>

      {/* List / Empty State */}
      {invoices.length === 0 ? (
        <div className="bg-white rounded-xl border p-12 text-center text-gray-400 text-sm">
          {t('invoices.empty') || 'No invoices yet'}
        </div>
      ) : (
        <div className="space-y-2">
          {invoices.map((inv) => (
            <div
              key={inv.id}
              className="bg-white rounded-xl border p-4 flex justify-between items-center hover:shadow-sm transition-shadow"
            >
              <div>
                <div className="font-semibold text-gray-800">
                  {clientName(inv)}
                </div>
                <div className="text-sm text-gray-500">
                  {t('invoices.dueDate') || 'Due'}:{' '}
                  {inv.dueDate
                    ? new Date(inv.dueDate).toLocaleDateString()
                    : '-'}
                </div>
              </div>
              <div className="text-right">
                <div className="font-bold text-lg text-gray-800">
                  ${inv.amount.toFixed(2)}
                </div>
                <span
                  className={`inline-block text-xs px-2 py-0.5 rounded-full ${
                    STATUS_CLASS[inv.status] || 'bg-gray-100 text-gray-600'
                  }`}
                >
                  {statusLabel(inv.status)}
                </span>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Add Invoice Modal */}
      {showForm && (
        <div
          className="fixed inset-0 bg-black/50 flex items-end sm:items-center justify-center z-50"
          onClick={() => setShowForm(false)}
        >
          <div
            className="bg-white rounded-t-2xl sm:rounded-2xl w-full sm:max-w-md p-6"
            onClick={(e) => e.stopPropagation()}
          >
            <h2 className="text-lg font-bold mb-4">
              {t('invoices.addTitle') || 'New Invoice'}
            </h2>
            <form onSubmit={handleAdd} className="space-y-3">
              <select
                className="w-full border rounded-lg px-3 py-2 text-sm"
                value={form.clientId}
                onChange={(e) =>
                  setForm({ ...form, clientId: e.target.value })
                }
                required
              >
                <option value="">
                  {t('invoices.selectClient') || 'Select client'}
                </option>
                {clients.map((c) => (
                  <option key={c.id} value={c.id}>
                    {c.name}
                  </option>
                ))}
              </select>
              <input
                className="w-full border rounded-lg px-3 py-2 text-sm"
                type="number"
                step="0.01"
                placeholder={`${t('invoices.amount') || 'Amount'} *`}
                value={form.amount}
                onChange={(e) =>
                  setForm({ ...form, amount: e.target.value })
                }
                required
              />
              <input
                className="w-full border rounded-lg px-3 py-2 text-sm"
                type="date"
                value={form.dueDate}
                onChange={(e) =>
                  setForm({ ...form, dueDate: e.target.value })
                }
              />
              <div className="flex gap-3 pt-2">
                <button
                  type="button"
                  onClick={() => setShowForm(false)}
                  className="flex-1 py-2 bg-gray-100 rounded-lg text-sm hover:bg-gray-200 transition-colors"
                >
                  {t('invoices.cancel') || 'Cancel'}
                </button>
                <button
                  type="submit"
                  className="flex-1 py-2 bg-indigo-600 text-white rounded-lg text-sm font-medium hover:bg-indigo-700 transition-colors"
                >
                  {t('invoices.confirm') || 'Create'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}

// uniapp/pages/invoices/invoices.vue
<template>
  <view class="page">
    <view class="header">
      <text class="title">发票管理</text>
      <button class="btn-add" @click="showForm = true">+ 新建</button>
    </view>

    <!-- Summary -->
    <view class="summary card">
      <view class="summary-item">
        <text class="summary-value">${{ totalRevenue }}</text>
        <text class="summary-label">总收入</text>
      </view>
      <view class="summary-item">
        <text class="summary-value pending">{{ pendingCount }}</text>
        <text class="summary-label">待收款</text>
      </view>
      <view class="summary-item">
        <text class="summary-value overdue">{{ overdueCount }}</text>
        <text class="summary-label">逾期</text>
      </view>
    </view>

    <view v-if="invoices.length === 0" class="empty">
      <text>暂无发票记录</text>
    </view>

    <view v-for="inv in invoices" :key="inv.id" class="invoice-card card">
      <view class="inv-left">
        <text class="inv-client">{{ inv.client?.name || '未知客户' }}</text>
        <text class="inv-date">到期: {{ formatDate(inv.dueDate) }}</text>
      </view>
      <view class="inv-right">
        <text class="inv-amount">${{ inv.amount.toFixed(2) }}</text>
        <text :class="['tag', 'tag-' + inv.status.toLowerCase()]">{{ statusLabel(inv.status) }}</text>
      </view>
    </view>

    <!-- Modal -->
    <view class="modal-mask" v-if="showForm" @click="showForm = false">
      <view class="modal" @click.stop>
        <text class="modal-title">新建发票</text>
        <picker class="picker" :range="clientNames" @change="onClientChange">
          <view class="picker-display">{{ clientNames[form.clientIdx] || '选择客户' }}</view>
        </picker>
        <input class="input" v-model="form.amount" type="digit" placeholder="金额 *" />
        <input class="input" v-model="form.dueDate" type="date" placeholder="到期日期" />
        <view class="modal-btns">
          <button class="btn-cancel" @click="showForm = false">取消</button>
          <button class="btn-primary" @click="handleAdd">确认创建</button>
        </view>
      </view>
    </view>
  </view>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue';

const showForm = ref(false);
const invoices = ref([]);
const allClients = ref([]);
const clientNames = ref(['请先添加客户']);

const form = ref({ clientIdx: 0, amount: '', dueDate: '' });

const totalRevenue = computed(() => invoices.value
  .filter((i: any) => i.status === 'PAID')
  .reduce((sum: number, i: any) => sum + i.amount, 0));

const pendingCount = computed(() => invoices.value.filter((i: any) => i.status === 'PENDING').length);
const overdueCount = computed(() => invoices.value.filter((i: any) => i.status === 'OVERDUE').length);

function formatDate(d) { return d ? new Date(d).toLocaleDateString('zh-CN') : ''; }
function statusLabel(s) {
  const map = { PENDING: '待付款', PAID: '已付款', OVERDUE: '逾期', REFUNDED: '已退款' };
  return map[s] || s;
}

function onClientChange(e) { form.value.clientIdx = e.detail.value; }

async function loadClients() {
  try {
    const res = await uni.request({ url: 'http://localhost:3000/api/clients' });
    if (res.statusCode === 200 && res.data) {
      allClients.value = res.data as any;
      clientNames.value = allClients.value.map((s: any) => s.name);
    }
  } catch (e) {}
}

async function loadInvoices() {
  try {
    const res = await uni.request({ url: 'http://localhost:3000/api/invoices' });
    if (res.statusCode === 200 && res.data) invoices.value = res.data as any;
  } catch (e) {}
}

async function handleAdd() {
  const client = allClients.value[form.value.clientIdx];
  if (!client) { uni.showToast({ title: '请选择客户', icon: 'none' }); return; }
  if (!form.value.amount) { uni.showToast({ title: '请输入金额', icon: 'none' }); return; }
  try {
    await uni.request({
      url: 'http://localhost:3000/api/invoices',
      method: 'POST',
      data: {
        clientId: (client as any).id,
        amount: parseFloat(form.value.amount),
        dueDate: form.value.dueDate || new Date(Date.now() + 7*86400000).toISOString().split('T')[0],
      },
    });
    uni.showToast({ title: '创建成功' });
    showForm.value = false;
    form.value = { clientIdx: 0, amount: '', dueDate: '' };
    loadInvoices();
  } catch (e) {
    uni.showToast({ title: '创建失败', icon: 'none' });
  }
}

onMounted(() => { loadClients(); loadInvoices(); });
</script>

<style scoped>
.page { background: #F0F2F5; min-height: 100vh; padding: 24rpx 32rpx; }
.header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 24rpx; }
.title { font-size: 36rpx; font-weight: 800; color: #1F2937; }
.btn-add { background: #4F46E5; color: #fff; padding: 12rpx 28rpx; border-radius: 12rpx; font-size: 26rpx; font-weight: 600; border: none; }

.summary { display: flex; justify-content: space-around; padding: 32rpx 0; }
.summary-item { text-align: center; }
.summary-value { font-size: 40rpx; font-weight: 800; color: #10B981; display: block; }
.summary-value.pending { color: #F59E0B; }
.summary-value.overdue { color: #EF4444; }
.summary-label { font-size: 22rpx; color: #9CA3AF; display: block; margin-top: 4rpx; }

.invoice-card { display: flex; justify-content: space-between; align-items: center; }
.inv-left { flex: 1; }
.inv-client { font-size: 30rpx; font-weight: 600; color: #1F2937; display: block; }
.inv-date { font-size: 24rpx; color: #6B7280; display: block; margin-top: 2rpx; }
.inv-right { text-align: right; }
.inv-amount { font-size: 34rpx; font-weight: 800; color: #1F2937; display: block; }

.empty { text-align: center; padding: 100rpx 0; color: #9CA3AF; }

.modal-mask { position: fixed; inset: 0; background: rgba(0,0,0,0.5); display: flex; align-items: flex-end; z-index: 999; }
.modal { width: 100%; background: #fff; border-radius: 32rpx 32rpx 0 0; padding: 48rpx 32rpx 60rpx; }
.modal-title { font-size: 34rpx; font-weight: 700; display: block; margin-bottom: 32rpx; }
.input, .picker-display {
  width: 100%; background: #F9FAFB; border: 2rpx solid #E5E7EB;
  border-radius: 12rpx; padding: 20rpx 24rpx; font-size: 28rpx; margin-bottom: 20rpx;
}
.modal-btns { display: flex; gap: 20rpx; margin-top: 32rpx; }
.btn-cancel { flex: 1; padding: 24rpx 0; border-radius: 12rpx; background: #F3F4F6; color: #6B7280; font-size: 28rpx; border: none; }
.btn-primary { flex: 1; padding: 24rpx 0; border-radius: 12rpx; font-size: 28rpx; }
</style>
